# Generated by Django 4.1.4 on 2022-12-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_api", "0002_audio_delete_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
